# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.10.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.10.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Robin/Development/learnllvm/bosojowo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Robin/Development/learnllvm/bosojowo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Robin/Development/learnllvm/bosojowo/CMakeFiles /Users/Robin/Development/learnllvm/bosojowo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Robin/Development/learnllvm/bosojowo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bosojowo

# Build rule for target.
bosojowo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bosojowo
.PHONY : bosojowo

# fast build rule for target.
bosojowo/fast:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/build
.PHONY : bosojowo/fast

#=============================================================================
# Target rules for targets named parser.cpp

# Build rule for target.
parser.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser.cpp
.PHONY : parser.cpp

# fast build rule for target.
parser.cpp/fast:
	$(MAKE) -f CMakeFiles/parser.cpp.dir/build.make CMakeFiles/parser.cpp.dir/build
.PHONY : parser.cpp/fast

#=============================================================================
# Target rules for targets named tokens.cpp

# Build rule for target.
tokens.cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tokens.cpp
.PHONY : tokens.cpp

# fast build rule for target.
tokens.cpp/fast:
	$(MAKE) -f CMakeFiles/tokens.cpp.dir/build.make CMakeFiles/tokens.cpp.dir/build
.PHONY : tokens.cpp/fast

codegen.o: codegen.cpp.o

.PHONY : codegen.o

# target to build an object file
codegen.cpp.o:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/codegen.cpp.o
.PHONY : codegen.cpp.o

codegen.i: codegen.cpp.i

.PHONY : codegen.i

# target to preprocess a source file
codegen.cpp.i:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/codegen.cpp.i
.PHONY : codegen.cpp.i

codegen.s: codegen.cpp.s

.PHONY : codegen.s

# target to generate assembly for a file
codegen.cpp.s:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/codegen.cpp.s
.PHONY : codegen.cpp.s

parser.o: parser.cpp.o

.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i

.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s

.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/parser.cpp.s
.PHONY : parser.cpp.s

stringutil.o: stringutil.cpp.o

.PHONY : stringutil.o

# target to build an object file
stringutil.cpp.o:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/stringutil.cpp.o
.PHONY : stringutil.cpp.o

stringutil.i: stringutil.cpp.i

.PHONY : stringutil.i

# target to preprocess a source file
stringutil.cpp.i:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/stringutil.cpp.i
.PHONY : stringutil.cpp.i

stringutil.s: stringutil.cpp.s

.PHONY : stringutil.s

# target to generate assembly for a file
stringutil.cpp.s:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/stringutil.cpp.s
.PHONY : stringutil.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/test.cpp.s
.PHONY : test.cpp.s

tokens.o: tokens.cpp.o

.PHONY : tokens.o

# target to build an object file
tokens.cpp.o:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/tokens.cpp.o
.PHONY : tokens.cpp.o

tokens.i: tokens.cpp.i

.PHONY : tokens.i

# target to preprocess a source file
tokens.cpp.i:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/tokens.cpp.i
.PHONY : tokens.cpp.i

tokens.s: tokens.cpp.s

.PHONY : tokens.s

# target to generate assembly for a file
tokens.cpp.s:
	$(MAKE) -f CMakeFiles/bosojowo.dir/build.make CMakeFiles/bosojowo.dir/tokens.cpp.s
.PHONY : tokens.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bosojowo"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... parser.cpp"
	@echo "... tokens.cpp"
	@echo "... codegen.o"
	@echo "... codegen.i"
	@echo "... codegen.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... stringutil.o"
	@echo "... stringutil.i"
	@echo "... stringutil.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... tokens.o"
	@echo "... tokens.i"
	@echo "... tokens.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

